version: "3.8"

services:
  mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    networks:
      - movies-network
    volumes:
      - db:/data/db
      - ./tp2-movies-backend/mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  backend:
    image: aymen06/tp2-6246005-backend:v1
    build:
      context: ./tp2-movies-backend
    ports:
      - "8080:8080"
    networks:
      - movies-network
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/movie-api-db?authSource=admin
      - SERVER_PORT=8080

  frontend:
    image: aymen06/tp2-6246005-frontend:v1
    build:
      context: ./tp2-movies-frontend
    ports:
      - "7777:80"
    depends_on:
      - backend
    networks:
      - movies-network

volumes:
  db:

networks:
  movies-network:
    driver: bridge


